### ISSUE TITLE
Error [ERR_MODULE_RESOLUTION_LEGACY]

### ISSUE THREAD

**Issue by GrosSacASac** [stefanpenner/mocha-esm#9]
https://github.com/GrosSacASac/event-e3

to reproduce: download, then `npm i`, then `npm test`

```
Error [ERR_MODULE_RESOLUTION_LEGACY]: C:\files\github\emitter\test\EventEmitter3.spec.mjs not found by import in file://
/C:/files/github/emitter/node_modules/mocha-esm/index.mjs. Legacy behavior in require() would have found it at C:\files\
github\emitter\test\EventEmitter3.spec.mjs
    at search (internal/modules/esm/default_resolve.js:38:15)
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:64:11)
    at Loader.resolve (internal/modules/esm/loader.js:58:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:113:40)
    at Loader.import (internal/modules/esm/loader.js:99:28)
    at setImportModuleDynamicallyCallback (internal/process/esm_loader.js:66:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! Test failed.  See above for more details.
```

**Comment by stefanpenner** [comment]
Thanks, i'll try to find some time to dig in.

**Comment by GrosSacASac** [comment]
node -v v10.9.0
